### ISSUE TITLE
请问，打印图片、二维码、网页应该发送什么内容或命令呢？

### ISSUE THREAD

**Issue by all-power** [south-pacific/cordova-plugin-bluetoothprinter#1]
您好，
非常感谢您开发的“cordova-plugin-bluetoothprinter”插件，使一个菜鸟也可以很快学会使用，已经成功连接了蓝牙打印机，可以成功打印文字，但还有一点疑问想向您请教，就是如果打印图片、二维码、网页应该发送什么内容或命令呢？多有打扰，感谢您 ：）

**Comment by south-pacific** [comment]
额，这个我这插件没有哈。具体怎么实现可能需要你自己研究下

**Comment by all-power** [comment]
感谢回复：）   那我自己研究研究哈~
