### ISSUE TITLE
您好，这个插件可以正常使用吗？

### ISSUE THREAD

**Issue by liangqiangkun** [south-pacific/cordova-plugin-bluetoothprinter#2]
@south-pacific  您好，您这个插件是自己做的，肯定是测试过可以正常使用的吧！我现在需要这样一个能力，另外我也是一个cordova 的开发者，期待与您技术交流！qq：1397743129

**Comment by south-pacific** [comment]
我已经很久没做cordova了，这个插件是之前做的，能正常使用。
