### ISSUE TITLE
关于cordova-plugin-bluetoothprinter 插件

### ISSUE THREAD

**Issue by kiss1952** [south-pacific/cordova-plugin-bluetoothprinter#3]
我本人不会写ios代码，所以想麻烦作者，是否可以完善ios的蓝牙打印机链接这块。整个插件 ios端 我貌似不能正常使用，关于蓝牙打印，我用的安卓的插件都是通过Mac地址打印，作者这里用的貌似不是mac地址。不知道是uuid还是name, 可以指教一下吗？谢谢

**Comment by south-pacific** [comment]
这个是好几年前写的了，我也好久没做过ios开发了，实在是抱歉。

**Comment by kiss1952** [comment]
抱歉，我今天才看到，前几天在开发接口。真的很抱歉。不管怎么说，都很感谢你
